apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod-luscsi-share
spec:
  containers:
    - name: busybox-container
      image: busybox:1.36
      args:
        - /bin/sh
        - -c
        - sleep 3600
      volumeMounts:
        - name: busybox-volume
          mountPath: /data
  volumes:
    - name: busybox-volume
      persistentVolumeClaim:
        claimName: luscsi-volume-share
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: luscsi-volume-share
spec:
  volumeName: lustre-share-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lustre-share-storage
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  csi:
    driver: luscsi.luskits.io
    volumeAttributes:
      mgsAddress: "10.6.118.91@tcp"
      fsName: "debug-fs"
      subDir: "" # let this be empty, only mount the sharePath to container
      sharePath: "share/storage/path" # this is the sharePath exist in lustre
      volumeID: "lustre-share-storage"
    volumeHandle: 10.6.118.91@tcp#debug-fs#share/storage/path#lustre-share-storage
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem