name: Release Chart

on:
  push:
    branches:
      - main
    paths:
      - "deploy/luscsi/Chart.yaml"

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1
      - name: Render Chart Values
        run: |
          make render-chart-values
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.3.0
        with:
          charts_dir: deploy
          charts_repo_url: https://luskits.github.io/luscsi/
          config: deploy/.cr/config.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  release-image:
    runs-on: ubuntu-latest
    needs:
      - release-chart
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - name: Login registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Set env
        run: |
          echo "IMAGE_VERSION=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
          echo "PROJECT_SOURCE_CODE_DIR=`echo ${GITHUB_WORKSPACE}`" >> $GITHUB_ENV
      - name: Release image
        run: |
          IMAGE_VERSION=${IMAGE_VERSION} make release
